# fly.toml app configuration file generated for gd-format-backend-black-breeze-3291 on 2024-01-07T01:30:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gd-format-backend-black-breeze-3291"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
